### ISSUE TITLE
The extension only works when the panel is open

### ISSUE THREAD

**Issue by 35609902357** [MrOtherGuy/bookmark-batch-updater#2]
When leaving the panel (for example to copy a URL) every already input value gets lost and when the extension is working the process is interrupted if the panel is closed by clicking anywhere in the window (or in other windows).

**Comment by MrOtherGuy** [comment]
Are you certain that the update process is interrupted when the popup closes? This is not supposed to happen anymore, and the update should continue in the background.

If you close the popup whilst the update is running and the reopen it, then the popup is supposed to show you progress of the update process and not accept any inputs.

It is true that values input to the fields do get lost when popup is closed though.

**Comment by 35609902357** [comment]
Apparently, if I start the scan it keeps going after the panel is closed, but as I open it again the fields are reset, so it is the same in the end. The panel should be made persistent at least until the tab is reloaded/closed or the user switches to another tab, which is important because like this copy-pasting is impossible because once the address bar is clicked, the panel is closed and the fields are reset.

**Comment by MrOtherGuy** [comment]
Latest version open the UI in a new tab so I'm closing this issue as invalid
