### ISSUE TITLE
suggestion: ignore local URLs by default

### ISSUE THREAD

**Issue by ghost** [MrOtherGuy/bookmark-batch-updater#5]
The 'http-to-https' feature of the addon should ignore local URLs such as `192.168.1.1` (modem) and `127.0.0.1` (e.g. [Jackett](https://github.com/Jackett/Jackett)) since they aren't expected to ever be behind HTTPS. "Upgrading" the bookmarks to `https://` from `http://` likely breaks access.

**Comment by MrOtherGuy** [comment]
Sounds reasonable. I'd think it should only affect http-to-https because if you are doing any other operation then it plausible that one would want to modify those bookmarks anyway. Do you agree?

This should be a super easy fix if I manage to fix #3

**Comment by ghost** [comment]
> Sounds reasonable. I'd think it should only affect http-to-https because if you are doing any other operation then it plausible that one would want to modify those bookmarks anyway. Do you agree?

Yes and that's what I meant. 

There may be more common IP strings, I listed the ones I was able to recall.

**Comment by MrOtherGuy** [comment]
This should be fixed by cf1d1a593919f87df9108ed4ea32519f0e1b556b

Some local, javascript: and data: urls are now excluded by default

**Comment by ghost** [comment]
> This should be fixed by [cf1d1a5](https://github.com/MrOtherGuy/bookmark-batch-updater/commit/cf1d1a593919f87df9108ed4ea32519f0e1b556b)
> 
> Some local, javascript: and data: urls are now excluded by default

Good, I forgot the bookmarklets!
